package com.c354.cycleapp;

import com.kingaspx.util.BrowserUtil;
import com.kingaspx.version.Version;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.events.ConsoleEvent;
import com.teamdev.jxbrowser.chromium.events.FinishLoadingEvent;
import com.teamdev.jxbrowser.chromium.events.LoadAdapter;
import com.teamdev.jxbrowser.chromium.events.TitleEvent;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JList;

public class CycleApp extends JFrame {

    public CycleApp() {
        initComponents();
        open_site();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        map_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        rideLabel = new javax.swing.JLabel();
        intervalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(225, 239, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 153, 255));
        titleLabel.setText("Cycle App");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        map_panel.setLayout(new java.awt.BorderLayout());
        jPanel1.add(map_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 360, 390));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Workout 2021-06-06", "Workout 2021-06-18", "Workout 2021-07-10", "Workout 2021-07-17" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, 110));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 km", "5 km", "10 km", "15 km" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 60, -1));

        rideLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rideLabel.setText("Ride List");
        jPanel1.add(rideLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        intervalLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        intervalLabel.setText("Select split interval:");
        jPanel1.add(intervalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 640));

        setBounds(0, 0, 372, 646);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CycleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CycleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CycleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CycleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CycleApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel intervalLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel map_panel;
    private javax.swing.JLabel rideLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    Browser browser;
    BrowserView view;

    private void open_site() {
        BrowserUtil.setVersion(Version.V6_22);

        browser = new Browser();
        view = new BrowserView(browser);

        map_panel.add(view, BorderLayout.CENTER);

        browser.addTitleListener((TitleEvent evt) -> {
            setTitle(evt.getTitle());
        });
        browser.addConsoleListener((ConsoleEvent evt) -> {
            System.out.println("LOG: " + evt.getMessage());
        });

        browser.addLoadListener(new LoadAdapter() {
            @Override
            public void onFinishLoadingFrame(FinishLoadingEvent evt) {
                evt.getBrowser().setZoomLevel(-2);
            }
        ;
        });
        browser.loadURL("C:\\HTMLGmaps\\simple_map.html");

        jList1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                JList list = (JList) evt.getSource();
                if (evt.getClickCount() == 2) {
                    int index = jList1.locationToIndex(evt.getPoint());
                    switch (index) {
                        case 0:
                            browser.loadHTML("<iframe src=\"https://gpx.studio/?state=%7B%22ids%22:%5B%221ETBK7UyreipM5Gr7TtFb0cg4nap2O_Fu%22%5D%7D&embed&token=pk.eyJ1IjoiYzM1NGdwIiwiYSI6ImNsMTkzdzFvMDR5OTUzYnBrOG1lOG84ODkifQ.5z_eVrxohLKmHzXqaZAxdw&running&distance&direction\" width=\"100%\" height=\"500\" frameborder=\"0\" allowfullscreen><p><a href=\"https://gpx.studio/?state=%7B%22ids%22:%5B%221ETBK7UyreipM5Gr7TtFb0cg4nap2O_Fu%22%5D%7D></a></p></iframe>");
                            break;
                        case 1:
                            browser.loadHTML("<iframe src=\"https://gpx.studio/?state=%7B%22ids%22:%5B%221HpeedYjC51JP4j84kHMNz7LfOmadvAwT%22%5D%7D&embed&token=pk.eyJ1IjoiYzM1NGdwIiwiYSI6ImNsMTkzdzFvMDR5OTUzYnBrOG1lOG84ODkifQ.5z_eVrxohLKmHzXqaZAxdw&running&distance&direction\" width=\"100%\" height=\"500\" frameborder=\"0\" allowfullscreen><p><a href=\"https://gpx.studio/?state=%7B%22ids%22:%5B%221HpeedYjC51JP4j84kHMNz7LfOmadvAwT%22%5D%7D></a></p></iframe>");
                            break;
                        case 2:
                            browser.loadHTML("<iframe src=\"https://gpx.studio/?state=%7B%22ids%22:%5B%2218ehq0zBMpCWv3N8eubdHLT9Q0__CQeOR%22%5D%7D&embed&token=pk.eyJ1IjoiYzM1NGdwIiwiYSI6ImNsMTkzdzFvMDR5OTUzYnBrOG1lOG84ODkifQ.5z_eVrxohLKmHzXqaZAxdw&running&distance&direction\" width=\"100%\" height=\"500\" frameborder=\"0\" allowfullscreen><p><a href=\"https://gpx.studio/?state=%7B%22ids%22:%5B%2218ehq0zBMpCWv3N8eubdHLT9Q0__CQeOR%22%5D%7D></a></p></iframe>");
                            break;
                        case 3:
                            browser.loadHTML("<iframe src=\"https://gpx.studio/?state=%7B%22ids%22:%5B%221LbMiqc5WxSGvDOiMMA-s2Ar5JzYCBH_V%22%5D%7D&embed&token=pk.eyJ1IjoiYzM1NGdwIiwiYSI6ImNsMTkzdzFvMDR5OTUzYnBrOG1lOG84ODkifQ.5z_eVrxohLKmHzXqaZAxdw&running&distance&direction\" width=\"100%\" height=\"500\" frameborder=\"0\" allowfullscreen><p><a href=\"https://gpx.studio/?state=%7B%22ids%22:%5B%221LbMiqc5WxSGvDOiMMA-s2Ar5JzYCBH_V%22%5D%7D></a></p></iframe>");
                            break;
                        default:
                            break;
                    }
                }
            }
        });
    }
}
